### ISSUE TITLE
i install it on my steamdeck but, its wrong.plz help me

### ISSUE THREAD

**Issue by 2413707988** [ALEZ-DEV/Babylonia-terminal#10]
(deck@steamdeck Desktop)$ bash <(curl -s https://raw.githubusercontent.com/ALEZ-DEV/Babylonia-terminal/master/build.sh)
Are you on steam deck? (y/n): y
Warning: The rootfs is already read-write!
         Nothing is performed.
Distrobox named 'babylonia-terminal-image' already exists.
To enter, run:

distrobox-enter babylonia-terminal-image

Container babylonia-terminal-image is not running.
Starting container babylonia-terminal-image
run this command to follow along:

 podman logs -f babylonia-terminal-image

Error: unable to start container "3b0cc58101505839e8b3035d50be9cae2f4fa03031acf85c8c9afc0615396de5": crun: setrlimit `RLIMIT_NPROC`: Operation not permitted: OCI permission denied
Container babylonia-terminal-image is not running.
Starting container babylonia-terminal-image
run this command to follow along:

 podman logs -f babylonia-terminal-image

Error: unable to start container "3b0cc58101505839e8b3035d50be9cae2f4fa03031acf85c8c9afc0615396de5": crun: setrlimit `RLIMIT_NPROC`: Operation not permitted: OCI permission denied
Container babylonia-terminal-image is not running.
Starting container babylonia-terminal-image
run this command to follow along:

 podman logs -f babylonia-terminal-image

Error: unable to start container "3b0cc58101505839e8b3035d50be9cae2f4fa03031acf85c8c9afc0615396de5": crun: setrlimit `RLIMIT_NPROC`: Operation not permitted: OCI permission denied
Container babylonia-terminal-image is not running.
Starting container babylonia-terminal-image
run this command to follow along:

 podman logs -f babylonia-terminal-image

Error: unable to start container "3b0cc58101505839e8b3035d50be9cae2f4fa03031acf85c8c9afc0615396de5": crun: setrlimit `RLIMIT_NPROC`: Operation not permitted: OCI permission denied
(125)(deck@steamdeck Desktop)$

**Comment by ALEZ-DEV** [comment]
Hey, thank for your interest on this project!

can you try to run the command as root, like below :
```sh
sudo bash <(curl -s https://raw.githubusercontent.com/ALEZ-DEV/Babylonia-terminal/master/build.sh)
```
and tell me if the error is different or not

**Comment by 2413707988** [comment]
only back this:

bash: /dev/fd/63: 没有那个文件或目录

**Comment by ALEZ-DEV** [comment]
I made some research on my side and it seem that your error require some technical knowledge on the subject to be able to fix it,
you can try to fix this error on your side or wait that I package the launcher into a flatpak.

I will notify you when the flatpak is ready

**Comment by 2413707988** [comment]
thx
ill wait for it

**Comment by ALEZ-DEV** [comment]
Hey,

Sorry for the wait, here it is, you have now the possibility to download the flatpak version.
For that you will need to add the anime launcher repository to your flatpak :
```bash
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo # you need the flathub repository if not already installed
flatpak remote-add --if-not-exists launcher.moe https://gol.launcher.moe/gol.launcher.moe.flatpakrepo
```
and you can after to to your software manager and search for `Babylonia Terminal`  
or you can directly install it with the following command :
```bash
flatpak install moe.celica.BabyloniaTerminal
```
be aware that the GUI version of the launcher is still in early stage, so expect bug (would be cool if you can report it by making an issue),
have fun!

**Comment by ALEZ-DEV** [comment]
Please fill a new issue if you're not able to run the game via the flatpak version, because I didn't had the time to check that, thanks!

**Comment by 2413707988** [comment]
> Please fill a new issue if you're not able to run the game via the flatpak version, because I didn't had the time to check that, thanks!

That was not what I meant，The flatpak version is able to run.
I just can't click on a icon to run the launcher
