### ISSUE TITLE
Where is the game path

### ISSUE THREAD

**Issue by 2413707988** [ALEZ-DEV/Babylonia-terminal#13]
I need to change to the Chinese version

**Comment by 2413707988** [comment]
I found it

**Comment by ALEZ-DEV** [comment]
> I need to change to the Chinese version

You want to play the chinese version of the game ?

**Comment by 2413707988** [comment]
> > I need to change to the Chinese version
> 
> You want to play the chinese version of the game ?

yes,I need this🥲
Now I replaced the game files, but that means I need to re-download and transfer to linux on my PC the next time the game is updated

**Comment by ALEZ-DEV** [comment]
That's something I wanted to implement soon, because some people help me out for that, if you really want it, please fill out a new issue to see the progress
