### ISSUE TITLE
Gigabit or Gigabyte?

### ISSUE THREAD

**Issue by My1** [ALEZ-DEV/Babylonia-terminal#16]
Gb is Gigabit, GB is Gigabyte (the most correct option would likely be GiB tho, which is already widely used on linux)

https://github.com/ALEZ-DEV/Babylonia-terminal/blob/fb4e47eac72678a114b38f4a0abd8db4e9aec552/babylonia_terminal_launcher/lib/widgets/steps/game_steps_widget.dart#L121

**Comment by ALEZ-DEV** [comment]
I will change this as soon as I can or you can make a PR if you want

**Comment by My1** [comment]
I am currently trying out what unit it's even trying to report (like if it's actually be Gigabit or whatever, it would need to be converted) but I obviously know nothing really about the language, let alone the framework, just some general programming knowledge and trying to follow the chain while googling anything on the way XD

**Comment by ALEZ-DEV** [comment]
I checked and I think it's bytes which are downloaded, so we need to write it as `GB` or `GiB`

and btw when checking the code I saw I made really dumb conversion, if you can simplify it would be cool :
https://github.com/ALEZ-DEV/Babylonia-terminal/blob/fb4e47eac72678a114b38f4a0abd8db4e9aec552/babylonia_terminal_launcher/lib/widgets/steps/game_steps_widget.dart#L110-L111
