### ISSUE TITLE
Network error

### ISSUE THREAD

**Issue by iakuraa** [ALEZ-DEV/Babylonia-terminal#26]
![image](https://github.com/user-attachments/assets/91f6c4aa-7a5d-4322-be29-97bc8d12ed48)

Why am I getting this? My network is working completely fine no issues with other apps but this.

**Comment by iakuraa** [comment]
Welp, solved it. I used Cloudflare WARP to change my DNS or something. Maybe it's a me issue. Maybe I got banned lol?

**Comment by ALEZ-DEV** [comment]
I don't think you're banned and that's only your network configuration which give this error, being banned is another error message (If I recall right)
