### ISSUE TITLE
Black screen on 10-2 cutscene

### ISSUE THREAD

**Issue by maxy-lion** [ALEZ-DEV/Babylonia-terminal#8]
I can press space to pause/unpause it, but I can't skip it using G or move my mouse to click the buttons

**Comment by ALEZ-DEV** [comment]
Does this issue happen to only this specific cutscene ?

**Comment by maxy-lion** [comment]
Yes.

**Comment by ALEZ-DEV** [comment]
I'm currently adding the ability to have the logs of the game, until then you will need to wait

I will notify you when the logs are ready

**Comment by maxy-lion** [comment]
Alrighty! :)

**Comment by ALEZ-DEV** [comment]
Sorry for the wait, but you can get the log of the game

Please install the new version of the launcher by doing : 
```
cargo install --force --git https://github.com/ALEZ-DEV/Babylonia-terminal --bin --branch general-improvement
```
After that, start the game like you normaly do with the launcher, try starting the 10-2 cutscene in game, then stop the game and copy the content of `~/.babylonia-terminal/game.log` from your home directory

**Comment by maxy-lion** [comment]
Okay! Installing it now

**Comment by maxy-lion** [comment]
It works now! I was able to get past the black screen and into 10-2
This is the log file, it only has some errors loading plugins but everything works fine
[game.log](https://github.com/user-attachments/files/16740336/game.log)

**Comment by ALEZ-DEV** [comment]
It's very weird that your game just suddenly work, it's possible that you have installed the GStreamer library between the two test, but happy for you if all work finally fine!
